### ISSUE TITLE
`realpath --relative-to` not available in GitHub Actions

### ISSUE THREAD

**Issue by snomos** [divvun/compile-mermaid-markdown-action#1]
The default builder machines have the wrong version of `realpath`; here's from a debug statement:

```sh
realpath --help
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.
```

Cf https://unix.stackexchange.com/questions/622073/realpath-tells-me-my-directory-doesnt-exist-but-it-does

This: https://stackoverflow.com/questions/2564634/convert-absolute-path-into-relative-path-given-a-current-directory-using-bash suggests using a Python one-liner, but then the builder complains about `python` / `python3` not found.

[The offending line of code](https://github.com/divvun/compile-mermaid-markdown-action/blob/5498a8108987781f94dddc925e0ace9936d7ee74/entrypoint.sh#L141)

This needs to be resolved to build reliable paths for the mermaid-converted images, so that they can be properly and reliably referenced in the output documents. For whatever reason this worked with the original (abandoned) code, but as soon as a GH Action script points to this version of the Compile Mermaid markdown Action it stopped to work. Alas, the abandoned code is stuck at Mermaid 8.x, whereas this version gets the newest Mermaid actions (presently at 10.x).

**Comment by snomos** [comment]
A working solution could be to install [this implementation of realpath](https://github.com/xpack-dev-tools/realpath-xpack) as part of the GH Action.

**Comment by snomos** [comment]
I tried using https://github.com/jaxxstorm/action-install-gh-release to install the `grealpath` tool mentioned in the previous commit, but for whatever reason it fails in the installation verification step (see [log](https://github.com/giellalt/giellalt.github.io/actions/runs/5118049260/jobs/9201686666)). @flammie could you have a go at this?

**Comment by flammie** [comment]
I added realpath/gnu coreutils into the mermaid docker now. At least some images were regenerated with different colours :-)

**Comment by snomos** [comment]
From the log file:

```
Using MMDC version in node_modules/: 10.1.0
```

Also other debug statements in the log file shows that this is now solved. Thanks!
